baseurl = "https://flatpickr.js.org/"
languageCode = "en-us"
title = "flatpickr"
theme = "hugo-material-docs"
metadataformat = "toml"
canonifyurls = true
# Enable Google Analytics by entering your tracking id
googleAnalytics = ""
pygmentsCodeFences = true
pygmentsStyle = "manni"

[params]
    # General information
    author = "chmln"
    description = "A lightweight and powerful datetimepicker"
    copyright = "Released under the MIT license"

    # Repository
    provider = "GitHub"
    repo_url = "https://github.com/flatpickr/flatpickr"

    version = "v4"
    logo = "images/logo.png"
    favicon = "images/logo.png"

    permalink = "#"

    # Custom assets
    custom_css = [
        "site.css",
        "https://cdn.jsdelivr.net/npm/flatpickr@latest/dist/flatpickr.css",
        "https://cdn.jsdelivr.net/npm/flatpickr@latest/dist/plugins/confirmDate/confirmDate.css",
        "https://cdn.jsdelivr.net/npm/flatpickr@latest/dist/plugins/monthSelect/style.css"
    ]
    custom_js  = [
        "init.js",
        "https://cdn.jsdelivr.net/npm/flatpickr@latest/dist/flatpickr.js",
        "https://cdn.jsdelivr.net/npm/flatpickr@latest/dist/plugins/confirmDate/confirmDate.js",
        "https://cdn.jsdelivr.net/npm/flatpickr@latest/dist/plugins/weekSelect/weekSelect.js",
        "https://cdn.jsdelivr.net/npm/flatpickr@latest/dist/plugins/rangePlugin.js",
        "https://cdn.jsdelivr.net/npm/flatpickr@latest/dist/plugins/minMaxTimePlugin.js",
        "https://cdn.jsdelivr.net/npm/flatpickr@latest/dist/plugins/monthSelect/index.js",
        "flatpickr.js",
        "themer.js"
    ]

    [params.palette]
        primary = "blue"
        accent  = "light-blue"

    [params.font]
        text = "Libre Franklin"
        code = "Roboto Mono"
[taxonomies]

[social]
    twitter = ""
    github  = "flatpickr/flatpickr"
    email   = ""


[[menu.main]]
    name   = "Introduction"
    url    = "/"
    weight = 1

[[menu.main]]
    name   = "Getting Started"
    url    = "getting-started/"
    weight = 2

[[menu.main]]
    name   = "Examples"
    url    = "examples/"
    weight = 3

[[menu.main]]
    name   = "The Flatpickr Instance"
    url    = "instance-methods-properties-elements/"
    weight = 4


[[menu.main]]
    name   = "Events & Hooks"
    url    = "events/"
    weight = 5

[[menu.main]]
    name   = "Config Options"
    url    = "options/"
    weight = 7

[[menu.main]]
    name   = "Formatting Tokens"
    url    = "formatting/"
    weight = 8

[[menu.main]]
    name   = "Localization"
    url    = "localization/"
    weight = 9

[[menu.main]]
    name   = "Plugins"
    url    = "plugins/"
    weight = 10

[[menu.main]]
    name   = "Themes"
    url    = "themes/"
    weight = 11

[[menu.main]]
    name   = "Mobile Support"
    url    = "mobile-support/"
    weight = 12

[[menu.main]]
    name   = "IE9"
    url    = "ie9/"
    weight = 13

[[menu.main]]
    name   = "Updating from v2"
    url    = "updating-from-v2/"
    weight = 14


[blackfriday]
    smartypants = true
    fractions = true
    smartDashes = true
    plainIDAnchors = true
